version: "3"
services:

  proxy:
    build: ./services/proxy/.
    volumes: 
      - ./services/proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    links:
    - web
    - nodered
    - portainer
    networks:
      - deathstar

  web:
    image: hashicorp/http-echo
    command: ["-text", "deathstar"]
    expose:
      - 5678
    networks:
      - deathstar

  portainer:
    image: portainer/portainer
    restart: unless-stopped
    networks:
      - deathstar
    ports:
      - "9000:9000"
      - "8000:8000"
    expose:
      - 9000
      - 8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volumes/portainer/data:/data

  nodered:
    networks:
      - deathstar
    build: ./services/nodered/.
    restart: unless-stopped
    user: "0"
    privileged: true
    env_file: ./services/nodered/nodered.env
    ports: 
      - "1880:1880"
    expose:
      - 1880
    volumes:
      - /volumes/nodered/data:/data

  # plex:
  #   image: linuxserver/plex
  #   network_mode: host
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - VERSION=docker
  #     #- UMASK_SET=022 #optional
  #   volumes:
  #     - ./volumes/plex/config:/config
  #     #- ~/mnt/HDD/tvseries:/tv
  #     #- ~/mnt/HDD/movies:/movies
  #     - ./volumes/plex/transcode:/transcode
  #   restart: unless-stopped



  # pihole:
  #   container_name: pihole
  #   image: pihole/pihole:latest
  #   ports:
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #     - "67:67/udp"
  #     - "8089:80/tcp"
  #     #- "443:443/tcp"
  #   env_file:
  #     - ./services/pihole/pihole.env
  #   volumes:
  #      - ./volumes/pihole/etc-pihole/:/etc/pihole/
  #      - ./volumes/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
  #   dns:
  #     - 127.0.0.1
  #     - 1.1.1.1
  #   # Recommended but not required (DHCP needs NET_ADMIN)
  #   #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
  #   cap_add:
  #     - NET_ADMIN
  #   restart: unless-stopped

 
  # nextcloud:
  #   image: nextcloud
  #   container_name: nextcloud
  #   ports:
  #     - 9321:80
  #   volumes:
  #     - ./volumes/nextcloud/html:/var/www/html
  #   restart: unless-stopped
  #   depends_on: 
  #     - nextcloud_db
  #   links:
  #     - nextcloud_db

  # nextcloud_db:
  #   image: linuxserver/mariadb
  #   container_name: nextcloud_db
  #   volumes:
  #     - ./volumes/nextcloud/db:/config
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_PASSWORD=password
  #     - MYSQL_DATABASE=nextcloud
  #     - MYSQL_USER=nextcloud
  #   restart: unless-stopped

networks:
  deathstar: