version: "3"
services:
  web:
    image: hashicorp/http-echo
    command: ["-text", "hello world"]
    expose:
      - 5678
    networks:
      - deathstar
  proxy:
    build:
      context:  .
      dockerfile: Dockerfile
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    links:
    - web
    networks:
      - deathstar

networks:
    deathstar: